### ISSUE TITLE
Vagrant provision fails at [anitya-dev : Install Anitya into the virtualenv] | pep517/_in_process.py get_requires_for_build_wheel

### ISSUE THREAD

**Issue by alejojo** [release-monitoring/anitya#747]
Hi @Zlopez ,

I am trying to test anitya using vagrant but I have the following error.

```yaml
TASK [anitya-dev : Install Anitya into the virtualenv] *************************
fatal: [anitya]: FAILED! => changed=false 
  cmd:
  - /home/vagrant/.virtualenvs/anitya/bin/pip3
  - install
  - -e
  - file:///home/vagrant/devel
  - file:///home/vagrant/devel/anitya_schema
  msg: |-
    stdout: Processing /home/vagrant/devel/anitya_schema
    Obtaining file:///home/vagrant/devel
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'
      Complete output from command /home/vagrant/.virtualenvs/anitya/bin/python3 /home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1ne60t0y:
      Traceback (most recent call last):
        File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
          main()
        File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
          backend = _build_backend()
        File "/home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in _build_backend
          obj = getattr(obj, path_part)
      AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  
      ----------------------------------------
  
    :stderr: Command "/home/vagrant/.virtualenvs/anitya/bin/python3 /home/vagrant/.virtualenvs/anitya/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp1ne60t0y" failed with error code 1 in /home/vagrant/devel
	to retry, use: --limit @/tmp/anitya/ansible/vagrant-playbook.retry

```

I have seen on https://github.com/pypa/setuptools/issues/1694 that someone recommended you using `pip install -e --no-use-pep517 'file://whatever/vagrant/devel`.

Would this fix the issue? I've tried adding `--no-use-pep517` to https://github.com/release-monitoring/anitya/blob/master/ansible/roles/anitya-dev/tasks/main.yml#L85 and I get the following error:

```yaml
TASK [anitya-dev : Install Anitya into the virtualenv] *************************
fatal: [anitya]: FAILED! => changed=false 
  cmd:
  - /home/vagrant/.virtualenvs/anitya/bin/pip3
  - install
  - -e
  - --no-use-pep517
  - file:///home/vagrant/devel
  - file:///home/vagrant/devel/anitya_schema
  msg: |2-
  
    :stderr: --no-use-pep517 should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
	to retry, use: --limit @/tmp/anitya/ansible/vagrant-playbook.retry

PLAY RECAP *********************************************************************
anitya                     : ok=11   changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
